name: Push Docker Image

on:
  schedule:
    - cron: 0 0 * * *

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: warp-ubuntu-latest-x64-4x
    steps:
      - uses: docker/setup-buildx-action@v3.10.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6.16.0
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/hypermodeinc/dgraph-standalone:nightly
