name: ci-dgraph-system-upgrade-tests

on:
  pull_request:
    paths:
      - "**/*.go"
      - "**/go.mod"
      - "**/*.yml"
      - "**/Dockerfile"
      - "**/Makefile"
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - main
      - release/**

permissions:
  contents: read

jobs:
  dgraph-upgrade-tests:
    if: github.event.pull_request.draft == false
    runs-on: warp-ubuntu-latest-x64-4x
    timeout-minutes: 90
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Make Linux Build and Docker Image
        run: make docker-image
      - name: Clean Up Environment
        run: |
          #!/bin/bash
          # clean cache
          go clean -testcache
      - name: Run System Upgrade Tests
        run: |
          #!/bin/bash
          # go env settings
          export GOPATH=~/go
          # move the binary
          cp dgraph/dgraph ~/go/bin/dgraph
          # run the sytem upgrade tests
          go test -v -timeout=120m -failfast -tags=upgrade \
            github.com/hypermodeinc/dgraph/v25/systest/mutations-and-queries \
            github.com/hypermodeinc/dgraph/v25/systest/plugin \
            github.com/hypermodeinc/dgraph/v25/systest/multi-tenancy
          # clean up docker containers after test execution
          go clean -testcache
          # sleep
          sleep 5
